### ISSUE TITLE
Unselected component displayed when a component of the same name (but in a different product) is also selected

### ISSUE THREAD

**Issue by ahal** [mozilla/triage-center#79] opened 2020-08-19 15:31 UTC
This link:
https://mozilla.github.io/triage-center/?component=Testing%3AGeneral&component=Firefox+Build+System%3ATry

Displays triage links for the `Firefox Build System :: General` component. I believe it's happening because it's watching both a component in the `Firefox Build System` product (but not `General`), as well as a component called `General` (but not in the `Firefox Build System` product).

**Comment by emceeaich** [comment] 2020-08-19 23:02
This is a duplicate of #73.

**Closed** 2020-08-25 14:00 UTC
